[package]
name = "jazz-gym"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "0.6"
rustyline = "9.1.0"
rand = "0.3"
rodio = "0.15"
